development:
  adapter: postgresql
  encoding: unicode
  database: socrada_development

test:
  adapter: postgresql
  encoding: unicode
  database: socrada_test

production:
  adapter: postgresql
  encoding: unicode
  database: socrada_production